### ISSUE TITLE
Lazy-load exceptions on construct EEVO

### ISSUE THREAD

**Issue by ppavlidis** [ppavlidis/Gemma#27]
This seems most common in the visualization. Not dataset specific. For example

http://www.chibi.ubc.ca/Gemma/expressionExperiment/showExpressionExperiment.html?id=379

diagnostics tab, visualize PCA  (icons below scree plot)

 This is not the only place observed (see logs) but:

```
     at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:383)
        at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:375)
        at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:122)
        at org.hibernate.collection.PersistentSet.size(PersistentSet.java:162)
        at ubic.gemma.model.expression.experiment.ExpressionExperimentValueObject.<init>(ExpressionExperimentValueObject.java:138)
        at ubic.gemma.model.expression.experiment.ExpressionExperimentValueObject.<init>(ExpressionExperimentValueObject.java:123)
        at ubic.gemma.core.analysis.preprocess.svd.SVDServiceHelperImpl.getTopLoadedVectors(SVDServiceHelperImpl.java:202)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  
<snip>
        at ubic.gemma.web.controller.expression.experiment.DEDVController.getDEDVForPcaVisualization(DEDVController.java:440)
```

**Comment by tesar-stepan** [comment]
Will be fixed in 1.13.1
